# Header config
  [header]
    # FixIt 0.2.13 | CHANGED desktop header mode ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    # FixIt 0.2.13 | CHANGED mobile header mode ["sticky", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [header.title]
      # URL of the LOGO
      logo = "/icon.svg"
      # title name
      name = "é«˜ä½ã®ç„¡é™éƒ"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false
    # FixIt 0.2.12 | NEW Header subtitle config
    [header.subtitle]
      # subtitle name
      name = "forever young"
      # whether to use typeit animation for subtitle name
      typeit = true
  # Home page config
  [home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "mkdirhao@gmail.com"
      # URL of avatar shown in home page
      avatarURL = "/icon.svg"
      # FixIt 0.2.17 | NEW identifier of avatar menu link
      avatarMenu = ""
      # title shown in home page (HTML format is supported)
      title = "é«˜ä½ã®ç„¡é™éƒ"
      # subtitle shown in home page
      subtitle = "æ˜¥ã¯ç™¾èŠ±ãŒå’²ãã€ç§‹ã«ã¯æœˆãŒç¾ã—ã\nå¤ã«ã¯çˆ½ã‚„ã‹ãªé¢¨ãŒå¹ãã€å†¬ã«ã¯é›ªãŒé™ã‚‹\nè‹¥ã—å¿ƒé ­ã«æ›ãé–’äº‹ç„¡ã‹ã‚Œã°\nä¾¿ã¡æ˜¯ã‚Œäººé–“ã®å¥½ã²æ™‚ç¯€ãªã‚Š"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "ã‚‚ã—æ„è¦‹ãŒç•°ãªã‚‹å ´åˆã¯ã€ã‚ãªãŸãŒæ­£ã—ã„ã§ã™ã€‚ğŸ‘"
    # Home page posts
    [home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
  [page.reward]
      enable = true
      animation = true
      # position relative to post footer, optional values: ["before", "after"]
      position = "before"
      
      comment = "Buy me a coffee "
      # comment = "Buy me a coffee"
      # FixIt 0.2.18 | NEW display mode of QR code images, optional values: ["static", "fixed"], default: `static`
      mode = "fixed"
      [page.reward.ways]
       wechatpay = "/images/wechat.jpg"
       alipay = "/images/alipay.jpg"
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
  [social]
    Paypal = "mkdirhao"

  [author]
    name = "Hao"
    email = "mkdirhao@gmail.com"
    link = ""
    avatar = "/icon.svg"